In [1]:
import numpy as np

In [3]:
#converting list to array - 
lst = [1,2,3,4,5,6,7,8,9]
arr = np.array(lst)
type(arr)

numpy.ndarray

In [6]:
np.array(lst,ndmin=2)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Arrange - 
give it a start, stop, step values

In [12]:
np.arange(1,10)
np.arange(1,10,2) #here we defined 2 so data will have 2 steps at a time.

#it does the same thing as following - 
# for i in range(10):print(i)

array([1, 3, 5, 7, 9])

### Size function
- arr.size tells the size of the whole array
- np.size passed with 0 tells no. of rows
- np.size passed with 1 tells no. of columns

In [17]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
print('Total:',arr.size)
print("Rows: ",np.size(arr,0))
print("Columns: ",np.size(arr,1))

Total: 12
Rows:  4
Columns:  3


### Shape -

In [20]:
arr.shape 
# alternatively you can also use np.size(arr,0) np.size(arr,1)

(4, 3)

### Dtype - 

In [25]:
arr.dtype
arr2 = np.array([1.2,3.1,2.2])
arr2.dtype

dtype('float64')

### ndim -
tells the number of dimensions an array has.

In [31]:
arr2.ndim
arr.ndim

2

### np.zeros - 

In [35]:
np.zeros(shape=(3,5),dtype=int) #rows = 3 columns = 5

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### np.ones - 

In [36]:
np.ones(shape=(3,5),dtype=int) #rows = 3 columns = 5

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### np.random.randint - 

In [40]:
np.random.randint(low = 1, high = 10, size = 10)

array([9, 1, 2, 5, 7, 1, 5, 4, 6, 4], dtype=int32)

### reshape - 

In [43]:
arr.shape
arr.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

### flatten - 
the data of all the rows is shifted into a single row.

In [45]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3])

### copy - 

In [52]:
arr2 = arr
print('id of previous array',id(arr))
print('id of new array',id(arr2))
print(20*'-')
arr2 = np.copy(arr)
print('id of previous array',id(arr))
print('id of new array',id(arr2))

id of previous array 2439747393008
id of new array 2439747393008
--------------------
id of previous array 2439747393008
id of new array 2439748468144


- arr.min
- arr.max
- arr.sum

In [55]:
print(f'Min:{arr.min()}')
print(f'Max:{arr.max()}')
print(f'Sum:{arr.sum()}')

Min:1
Max:9
Sum:51


### Sorting function -

In [58]:
arr2 = np.array([3,4,2,5,1,4])
np.sort(arr2)

array([1, 2, 3, 4, 4, 5])

### Mean, Variance and Standard Deviation - 

In [62]:
print(arr.mean())
print(arr.var())
print(arr.std())

4.25
6.854166666666667
2.6180463454008347


In [68]:
arr3 = np.random.randint(1,50,20)
arr3<12 #true for all the arrays smaller than 12

array([ True, False, False, False,  True, False, False,  True, False,
       False, False, False, False, False, False, False, False,  True,
       False, False])

### Concatenation - 
remember that both the arrays should have same dimensions and data format. axis 0 will merge row wise and axis 1 will merge column wise

In [79]:
# np.concatenate((arr,arr2),axis=1)
arr4 = np.array([[2,3,3],[2,3,3],[2,3,3]])
np.concatenate((arr,arr4),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [2, 3, 3],
       [2, 3, 3],
       [2, 3, 3]])

### VStack and HStack - 

In [89]:
arr4 = np.random.randint(1,20,(4,3))
np.hstack((arr,arr4))

array([[ 1,  2,  3, 10,  5, 18],
       [ 4,  5,  6,  6, 19,  2],
       [ 7,  8,  9, 17,  4, 13],
       [ 1,  2,  3, 18, 11, 12]])

In [90]:
np.vstack((arr,arr4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  2,  3],
       [10,  5, 18],
       [ 6, 19,  2],
       [17,  4, 13],
       [18, 11, 12]])

### Splitting arrays - 

In [103]:
np.vsplit(arr,2) #splits the arrays in two parts 

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 2, 3]])]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

### Turning pics into numpy arrays - 

In [108]:
<img src='thar.jpg'>

SyntaxError: invalid syntax (2541680147.py, line 1)

In [110]:
from matplotlib.image import imread

In [111]:
img = imread('thar.jpg')

In [121]:
img.shape #1280 is pixels in height, 960 are pixels in width and 3 is the RGB channel

(1280, 960, 3)

In [125]:
np.min(img)

np.uint8(0)

In [128]:
img.size

3686400